#!/bin/bash
if [ -z "$TMUX" ] && [ "$TERM" != "screen" ]; then
  existingTmux=$(tmux ls |  cut -f 1 -d ":")
  if [ "" = "$existingTmux" ]; then
    tmux
  else
    tmux attach -t $existingTmux
  fi
fi
